name: Deploy to Lightsail

on:
  push:
    branches:
      - main # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      # - name: Create .env on server
      #   run: |
      #     ssh -t -t ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
      #       echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" > /home/bitnami/lightsail-nextjs/.env
      #       echo "NODE_ENV=production" >> /home/bitnami/lightsail-nextjs/.env
      #     EOF

      - name: Upload app
        run: |
          scp -i ~/.ssh/id_rsa -r . ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/home/bitnami/lightsail-nextjs

      - name: Deploy to Lightsail
        run: |
          ssh -tt -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "
            cd /home/bitnami/lightsail-nextjs &&
            npm install &&
            npm run build &&
            npx kill-port 3000 || true &&
            nohup npm run start > nextjs.log 2>&1 &"
