name: Deploy to Lightsail

on:
  push:
    branches:
      - main # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env on server
        run: |
          ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" > /opt/bitnami/lightsail-nextjs/.env
            echo "NODE_ENV=production" >> /opt/bitnami/lightsail-nextjs/.env
          EOF

      - name: Deploy to Lightsail
        run: |
          ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            cd /opt/bitnami/lightsail-nextjs
            git pull origin main
            npm install
            npm run build
            # Kill any existing process on port 3000 if needed
            lsof -ti:3000 | xargs kill -9 2>/dev/null || true
            # Start the production server
            nohup npm run start > nextjs.log 2>&1 &
          EOF
